Aeron causes the following problem;:
Warning: space is running low in /dev/shm (shm) threshold=167,772,160 usable=58,716,160
02:20:12.271UTC ERROR - swallowing exception during message send
io.aeron.exceptions.RegistrationException: correlationId=3, errorCodeValue=0, UncheckedIOException : java.io.IOException: No space left on device
at io.aeron.ClientConductor.onError(ClientConductor.java:237)
at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:115)
at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:68)
at io.aeron.ClientConductor.service(ClientConductor.java:1051)
at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:1098)
at io.aeron.ClientConductor.addPublication(ClientConductor.java:474)
at io.aeron.Aeron.addPublication(Aeron.java:259)